version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: api-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

